#ifndef BLITZNEXT_COMMANDS_H
#define BLITZNEXT_COMMANDS_H

#include "lexer.h" // toLower
#include <string>
#include <unordered_map>

// ---- Known commands --------------------------------------------------------
// Single source of truth for -k / +k output.
// Each entry: { "Name", "param1, param2, ..." }  (empty string = no params)

struct CmdInfo { const char *name; const char *sig; };

inline constexpr CmdInfo kCommands[] = {
  // Output / Input
  { "Print",    "value"              },
  { "WaitKey",  ""                   },
  { "Input",    "prompt$=\"\""       },
  // String — conversion
  { "Str",      "value"              },
  { "Int",      "s$"                 },
  { "Float",    "s$"                 },
  { "Len",      "s$"                 },
  // String — extraction (M19)
  { "Left",     "s$, n%"            },
  { "Right",    "s$, n%"            },
  { "Mid",      "s$, pos%"          },
  { "Instr",    "s$, sub$"          },
  { "Replace",  "s$, from$, to$"    },
  // String — transformation (M20)
  { "Upper",    "s$"                 },
  { "Lower",    "s$"                 },
  { "Trim",     "s$"                 },
  { "LSet",     "s$, n%"            },
  { "RSet",     "s$, n%"            },
  { "Chr",      "n%"                 },
  { "Asc",      "s$"                 },
  { "Hex",      "n%"                 },
  { "Bin",      "n%"                 },
  { "String",   "s$, n%"            },
  // Math — trig (M17)
  { "Sin",      "deg#"               },
  { "Cos",      "deg#"               },
  { "Tan",      "deg#"               },
  { "ASin",     "x#"                 },
  { "ACos",     "x#"                 },
  { "ATan",     "x#"                 },
  { "ATan2",    "y#, x#"            },
  // Math — general (M17)
  { "Sqr",      "x#"                 },
  { "Abs",      "x#"                 },
  { "Log",      "x#"                 },
  { "Log10",    "x#"                 },
  { "Exp",      "x#"                 },
  { "Floor",    "x#"                 },
  { "Ceil",     "x#"                 },
  { "Sgn",      "x#"                 },
  { "Pi",       ""                   },
  { "Min",      "a, b"               },
  { "Max",      "a, b"               },
  // Math — random (M18)
  { "Rnd",      ""                   },
  { "Rand",     "max%"               },
  { "SeedRnd",  "seed%"              },
  { "RndSeed",  ""                   },
  // Time / System
  { "Delay",    "ms%"                },
  // Sound (M34)
  { "LoadSound",   "file$"          },
  { "FreeSound",   "handle%"        },
  { "PlaySound",   "handle%"        },
  { "LoopSound",   "handle%"        },
  { "StopChannel", "channel%"       },
  // 2D Graphics — colour & pixel primitives (M40)
  { "Color",       "r%, g%, b%"   },
  { "ClsColor",    "r%, g%, b%"   },
  { "ColorRed",    ""             },
  { "ColorGreen",  ""             },
  { "ColorBlue",   ""             },
  { "GetColor",    "x%, y%"       },
  { "Plot",        "x%, y%"       },
  { "Rgb",         "r%, g%, b%"   },
  // 2D Graphics — shapes (M41)
  { "Line",        "x1%, y1%, x2%, y2%"              },
  { "Rect",        "x%, y%, w%, h% [,solid%]"         },
  { "Oval",        "x%, y%, w%, h% [,solid%]"         },
  { "Poly",        "x0%, y0%, x1%, y1%, x2%, y2%"    },
  // 2D Graphics — text (M42)
  { "Write",       "val"                                          },
  { "Locate",      "x%, y%"                                      },
  { "Text",        "x%, y%, s$ [,centerX%] [,centerY%]"          },
  // 2D Graphics — fonts (M43)
  { "LoadFont",    "name$, height% [,bold%] [,italic%] [,underline%]" },
  { "SetFont",     "handle%"                                      },
  { "FreeFont",    "handle%"                                      },
  { "FontWidth",   ""                                             },
  { "FontHeight",  ""                                             },
  { "StringWidth", "s$"                                          },
  { "StringHeight","s$"                                          },
  // 2D Graphics — images (M44)
  { "LoadImage",       "file$"                                                    },
  { "CreateImage",     "w%, h% [,frames%=1]"                                      },
  { "FreeImage",       "handle%"                                                   },
  { "ImageWidth",      "handle% [,frame%=0]"                                      },
  { "ImageHeight",     "handle% [,frame%=0]"                                      },
  { "DrawImage",       "handle%, x%, y% [,frame%=0]"                              },
  { "DrawImageRect",   "handle%, x%, y%, sx%, sy%, sw%, sh% [,frame%=0]"          },
  { "DrawBlock",       "handle%, x%, y% [,frame%=0]"                              },
  { "DrawBlockRect",   "handle%, x%, y%, sx%, sy%, sw%, sh% [,frame%=0]"          },
  // 2D Graphics — image manipulation (M45)
  { "HandleImage",     "handle%, x%, y% [,frame%=0]"                              },
  { "MidHandle",       "handle% [,frame%=0]"                                      },
  { "AutoMidHandle",   "on%"                                                       },
  { "ImageXHandle",    "handle% [,frame%=0]"                                      },
  { "ImageYHandle",    "handle% [,frame%=0]"                                      },
  { "ScaleImage",      "handle%, sx#, sy# [,frame%=0]"                            },
  { "RotateImage",     "handle%, deg# [,frame%=0]"                                },
  { "MaskImage",       "handle%, r%, g%, b% [,frame%=0]"                          },
  { "TileImage",       "handle%, x%, y% [,frame%=0]"                              },
  { "TileBlock",       "handle%, x%, y% [,frame%=0]"                              },
  { "DrawImageEllipse","handle%, x%, y%, rx%, ry% [,frame%=0]"                    },
  { "SaveImage",       "handle%, file$ [,frame%=0]"                               },
  { "ImagesOverlap",   "h1%, x1%, y1%, h2%, x2%, y2%"                             },
  { "ImageRectOverlap","handle%, x%, y%, rx%, ry%, rw%, rh%"                      },
  { "ImagesColl",      "h1%, x1%, y1%, h2%, x2%, y2%"                             },
  { "ImageXColl",      "h1%, x1%, y1%, h2%, x2%, y2%"                             },
  { "ImageYColl",      "h1%, x1%, y1%, h2%, x2%, y2%"                             },
  // 2D Graphics — animated images & new image API (M46b)
  { "LoadAnimImage",   "file$, fw%, fh%, first%, count%"                           },
  { "GrabImage",       "handle%, x%, y% [,frame%=0]"                              },
  { "CopyImage",       "handle%"                                                   },
  { "FlipImage",       "handle% [,frame%=0]"                                      },
  { "MirrorImage",     "handle% [,frame%=0]"                                      },
  { "ImagesCollide",   "h1%, x1%, y1%, f1%, h2%, x2%, y2%, f2%"                  },
  { "ImageRectCollide","handle%, x%, y%, frame%, rx%, ry%, rw%, rh%"              },
  // 2D Graphics — pixel buffer access (M46)
  { "ImageBuffer",      "handle% [,frame%=0]"                                      },
  { "LockBuffer",       "buf%"                                             },
  { "UnlockBuffer",     "buf%"                                             },
  { "ReadPixel",        "x%, y%, buf%"                                     },
  { "WritePixel",       "x%, y%, color%, buf%"                             },
  { "ReadPixelFast",    "x%, y%, buf%"                                     },
  { "WritePixelFast",   "x%, y%, color%, buf%"                             },
  { "CopyPixel",        "sx%, sy%, sbuf%, dx%, dy%, dbuf%"                 },
  { "CopyPixelFast",    "sx%, sy%, sbuf%, dx%, dy%, dbuf%"                 },
  { "LoadBuffer",       "buf%, file$"                                      },
  { "SaveBuffer",       "buf%, file$"                                      },
  { "BufferWidth",      "buf%"                                             },
  { "BufferHeight",     "buf%"                                             },
  // 2D Graphics — buffer & flip (M39)
  { "BackBuffer",  ""                                              },
  { "FrontBuffer", ""                                              },
  { "SetBuffer",   "buffer%"                                       },
  { "Cls",         ""                                              },
  { "Flip",        "vblank%=1"                                     },
  { "CopyRect",    "sx%, sy%, sw%, sh%, dx%, dy% [,src%] [,dst%]"  },
  { "Origin",      "x%, y%"                                        },
  { "Viewport",    "x%, y%, w%, h%"                                },
  // 2D Graphics — init (M38)
  { "Graphics",         "width%, height%, depth%=32, mode%=0" },
  { "EndGraphics",      ""                                     },
  { "GraphicsWidth",    ""                                     },
  { "GraphicsHeight",   ""                                     },
  { "GraphicsDepth",    ""                                     },
  { "GraphicsRate",     ""                                     },
  { "TotalVidMem",      ""                                     },
  { "AvailVidMem",      ""                                     },
  { "GraphicsMode",     "w%, h%, depth%, rate%"                },
  // 3D Graphics — init & scene control (3D-01 / 3D-02)
  { "Graphics3D",       "width%, height%, depth%=32, mode%=0" },
  { "UpdateWorld",      ""                                     },
  { "RenderWorld",      ""                                     },
  { "ClearWorld",       ""                                     },
  { "CaptureWorld",     ""                                     },
  { "TrisRendered",     ""                                     },
  { "Dither",           "on%"                                  },
  { "WBuffer",          "on%"                                  },
  { "AntiAlias",        "on%"                                  },
  { "Wireframe",        "on%"                                  },
  { "HWMultiTex",       "on%"                                  },
  { "AmbientLight",     "r%, g%, b%"                           },
  { "CameraClsMode",    "camera%, cls_color%=1, cls_zbuf%=1"   },
  { "CameraClsColor",   "camera%, r%, g%, b%"                  },
  // 3D Camera entity (3D-06)
  { "CreateCamera",     "parent%=0"                            },
  { "CameraRange",      "camera%, near#, far#"                 },
  { "CameraZoom",       "camera%, zoom#"                       },
  { "CameraProjMode",   "camera%, mode%"                       },
  { "CameraViewport",   "camera%, x%, y%, w%, h%"              },
  // 3D Primitive Meshes (3D-09)
  { "CreateCube",       "parent%=0"                            },
  { "CreateSphere",     "segs%=8, parent%=0"                   },
  { "CreateCylinder",   "segs%=8, open%=0, parent%=0"         },
  { "CreateCone",       "segs%=8, open%=0, parent%=0"         },
  { "MeshWidth",        "mesh%"                                },
  { "MeshHeight",       "mesh%"                                },
  { "MeshDepth",        "mesh%"                                },
  // 3D Entity system (3D-03)
  { "CreatePivot",      "parent%=0"                            },
  { "FreeEntity",       "entity%"                              },
  { "HideEntity",       "entity%"                              },
  { "ShowEntity",       "entity%"                              },
  { "NameEntity",       "entity%, name$"                       },
  { "EntityName",       "entity%"                              },
  // 3D Transform system (3D-04)
  { "PositionEntity",   "entity%, x#, y#, z#, global%=0"      },
  { "MoveEntity",       "entity%, dx#, dy#, dz#"              },
  { "TranslateEntity",  "entity%, dx#, dy#, dz#, global%=0"   },
  { "RotateEntity",     "entity%, rx#, ry#, rz#, global%=0"   },
  { "TurnEntity",       "entity%, rx#, ry#, rz#, global%=0"   },
  { "ScaleEntity",      "entity%, sx#, sy#, sz#, global%=0"   },
  { "PointEntity",      "entity%, target%, roll#=0"           },
  { "AlignToVector",    "entity%, nx#, ny#, nz#, axis%, rate#=1" },
  { "ResetEntity",      "entity%"                              },
  { "EntityX",          "entity%, global%=0"                  },
  { "EntityY",          "entity%, global%=0"                  },
  { "EntityZ",          "entity%, global%=0"                  },
  { "EntityPitch",      "entity%, global%=0"                  },
  { "EntityYaw",        "entity%, global%=0"                  },
  { "EntityRoll",       "entity%, global%=0"                  },
  { "EntityDistance",   "entity1%, entity2%"                  },
  // 3D Hierarchy (3D-05)
  { "EntityParent",     "entity%, parent%, global%=0"         },
  { "GetParent",        "entity%"                             },
  { "FindChild",        "entity%, name$"                      },
  { "CountChildren",    "entity%"                             },
  { "GetChild",         "entity%, index%"                     },
  { "EntityOrder",      "entity%, order%"                     },
  { "EntityClass",      "entity%"                             },
  // 3D Sound (M37)
  { "Load3DSound",        "file$"                        },
  { "SoundRange",         "snd%, inner#, outer#"         },
  { "Channel3DPosition",  "ch%, x#, y#, z#"             },
  { "Channel3DVelocity",  "ch%, vx#, vy#, vz#"          },
  { "ListenerPosition",   "x#, y#, z#"                  },
  { "ListenerOrientation","fx#, fy#, fz#, ux#, uy#, uz#"},
  { "ListenerVelocity",   "vx#, vy#, vz#"               },
  { "WaitSound",          "ch%"                          },
  // Music & CD (M36)
  { "PlayMusic",    "file$"          },
  { "StopMusic",    ""               },
  { "MusicPlaying", ""               },
  { "PlayCDTrack",  "track%"         },
  // Channel control (M35)
  { "PauseChannel",   "channel%"              },
  { "ResumeChannel",  "channel%"              },
  { "ChannelPlaying", "channel%"              },
  { "ChannelVolume",  "channel%, vol#"        },
  { "ChannelPan",     "channel%, pan#"        },
  { "ChannelPitch",   "channel%, hz#"         },
  { "SoundVolume",    "handle%, vol#"         },
  { "SoundPan",       "handle%, pan#"         },
  { "SoundPitch",     "handle%, hz#"          },
  // Joystick (M33)
  { "JoyType",  "port%"             },
  { "JoyX",     "port%"             },
  { "JoyY",     "port%"             },
  { "JoyZ",     "port%"             },
  { "JoyU",     "port%"             },
  { "JoyV",     "port%"             },
  { "JoyHat",   "port%"             },
  { "JoyDown",  "port%, button%"    },
  { "JoyHit",   "port%, button%"    },
  { "WaitJoy",  "port%"             },
  { "GetJoy",   "port%"             },
  { "FlushJoy", "port%"             },
  // Keyboard (M31)
  { "KeyDown",      "key%"           },
  { "KeyHit",       "key%"           },
  { "GetKey",       ""               },
  { "FlushKeys",    ""               },
  // Mouse (M32)
  { "MouseX",       ""               },
  { "MouseY",       ""               },
  { "MouseZ",       ""               },
  { "MouseXSpeed",  ""               },
  { "MouseYSpeed",  ""               },
  { "MouseZSpeed",  ""               },
  { "MouseDown",    "button%"        },
  { "MouseHit",     "button%"        },
  { "WaitMouse",    ""               },
  { "GetMouse",     ""               },
  { "FlushMouse",   ""               },
  { "MoveMouse",    "x%, y%"         },
  // Events
  { "PollEvents",   ""               },
  // System (M28-M30)
  { "AppTitle",     "title$"         },
  { "MilliSecs",    ""               },
  { "CurrentDate",  ""               },
  { "CurrentTime",  ""               },
  { "RuntimeError", "msg$"           },
  { "Notify",       "msg$"           },
  { "Confirm",      "msg$"           },
  { "Proceed",      "msg$"           },
  { "CommandLine",  ""               },
  { "ExecFile",     "path$"          },
  { "GetEnv",       "name$"          },
  { "SetEnv",       "name$, val$"    },
  { "SystemProperty","prop$"         },
  { "ShowPointer",  ""               },
  { "HidePointer",  ""               },
  { "CreateTimer",  "hz%"            },
  { "WaitTimer",    "handle%"        },
  { "FreeTimer",    "handle%"        },
  { "CallDLL",      "dll$, func$, bank%, retbank%" },
  // File I/O (M25-M27)
  { "OpenFile",     "path$"          },
  { "ReadFile",     "path$"          },
  { "WriteFile",    "path$"          },
  { "CloseFile",    "handle%"        },
  { "FilePos",      "handle%"        },
  { "SeekFile",     "handle%, pos%"  },
  { "Eof",          "handle%"        },
  { "ReadAvail",    "handle%"        },
  { "WriteByte",    "handle%, val%"  },
  { "WriteShort",   "handle%, val%"  },
  { "WriteInt",     "handle%, val%"  },
  { "WriteFloat",   "handle%, val#"  },
  { "WriteString",  "handle%, s$"    },
  { "WriteLine",    "handle%, s$"    },
  { "ReadByte",     "handle%"        },
  { "ReadShort",    "handle%"        },
  { "ReadInt",      "handle%"        },
  { "ReadFloat",    "handle%"        },
  { "ReadString",   "handle%"        },
  { "ReadLine",     "handle%"        },
  { "ReadDir",      "path$"          },
  { "NextFile",     "handle%"        },
  { "CloseDir",     "handle%"        },
  { "CurrentDir",   ""               },
  { "ChangeDir",    "path$"          },
  { "CreateDir",    "path$"          },
  { "DeleteDir",    "path$"          },
  { "FileType",     "path$"          },
  { "FileSize",     "path$"          },
  { "CopyFile",     "src$, dst$"     },
  { "DeleteFile",   "path$"          },
  // Bank (M24)
  { "CreateBank",   "size%"          },
  { "FreeBank",     "handle%"        },
  { "BankSize",     "handle%"        },
  { "ResizeBank",   "handle%, size%" },
  { "CopyBank",     "src%, srcoff%, dst%, dstoff%, len%" },
  { "PeekByte",     "handle%, offset%"  },
  { "PeekShort",    "handle%, offset%"  },
  { "PeekInt",      "handle%, offset%"  },
  { "PeekFloat",    "handle%, offset%"  },
  { "PokeByte",     "handle%, offset%, val%"  },
  { "PokeShort",    "handle%, offset%, val%"  },
  { "PokeInt",      "handle%, offset%, val%"  },
  { "PokeFloat",    "handle%, offset%, val#"  },
  { "ReadBytes",    "bank%, file%, offset%, count%" },
  { "WriteBytes",   "bank%, file%, offset%, count%" },
};

// Blitz3D is case-insensitive, the generated C++ is not: the runtime function
// for Print is bb_Print, whatever the source spelled. Returns the canonical
// spelling from kCommands[] for any casing of a built-in, or nullptr when the
// name is not a built-in command.
inline const char *canonicalCommand(const std::string &name) {
  static const std::unordered_map<std::string, const char *> byLower = [] {
    std::unordered_map<std::string, const char *> m;
    for (const auto &c : kCommands) m.emplace(toLower(c.name), c.name);
    return m;
  }();
  auto it = byLower.find(toLower(name));
  return (it == byLower.end()) ? nullptr : it->second;
}

#endif // BLITZNEXT_COMMANDS_H
