#ifndef BLITZNEXT_COMMANDS_H
#define BLITZNEXT_COMMANDS_H

#include "lexer.h" // toLower
#include <string>
#include <unordered_map>

// ---- Known commands -------------------------------------------------------
//
// ERZEUGT von scripts/gen_commands.py aus den Runtime-Headern
// (src/compiler/bb_*.h). NICHT VON HAND BEARBEITEN — Aenderungen gehen beim
// naechsten Lauf verloren. Wer einen Befehl hinzufuegt, schreibt ihn in die
// Runtime und laesst das Skript neu laufen; `--check` meldet Abweichungen.
//
// Damit ist die Tabelle per Konstruktion das, was der erzeugte C++-Code
// tatsaechlich aufruft (WEAK-17).
//
// Felder:
//   name   kanonische Schreibweise, z.B. "Print"
//   ret    Rueckgabetyp: "%" int, "#" float, "$" string, "" void,
//          "." uneinheitlich ueber Ueberladungen hinweg
//   params Kommaliste "name<typ>[?]", '?' = optional, fehlender Typ =
//          beliebig. Beispiel: "handle%,frame%?"

struct CmdInfo {
  const char *name;
  const char *ret;
  const char *params;
};

inline constexpr CmdInfo kCommands[] = {
  { "Abs",                 "#", "x#" },
  { "ACos",                "#", "x#" },
  { "ActiveTextures",      "%", "" },
  { "AlignToVector",       "",  "h%,nx#,ny#,nz#,axis%,rate#?" },
  { "AmbientLight",        "",  "r#,g#,b#" },
  { "AntiAlias",           "",  "arg1%" },
  { "AppTitle",            "",  "title$,close_prompt$?" },
  { "Asc",                 "%", "s$" },
  { "ASin",                "#", "x#" },
  { "ATan",                "#", "x#" },
  { "ATan2",               "#", "y#,x#" },
  { "AutoMidHandle",       "",  "on%" },
  { "AvailVidMem",         "%", "" },
  { "BackBuffer",          "%", "" },
  { "BankSize",            "%", "handle%" },
  { "Bin",                 "$", "n%" },
  { "BufferHeight",        "%", "buf%" },
  { "BufferWidth",         "%", "buf%" },
  { "CallDLL",             "%", "dll$,func$,in_bank%?,out_bank%?" },
  { "CameraClsColor",      "",  "h%,r%,g%,b%" },
  { "CameraClsMode",       "",  "h%,cls_color%,cls_zbuf%" },
  { "CameraProjMode",      "",  "h%,mode%" },
  { "CameraRange",         "",  "h%,near_clip#,far_clip#" },
  { "CameraViewport",      "",  "h%,x%,y%,w%,hh%" },
  { "CameraZoom",          "",  "h%,zoom#" },
  { "CaptureWorld",        "",  "" },
  { "Ceil",                "#", "x#" },
  { "ChangeDir",           "",  "path$" },
  { "Channel3DPosition",   "",  "ch%,x#,y#,z#" },
  { "Channel3DVelocity",   "",  "ch%,vx#,vy#,vz#" },
  { "ChannelPan",          "",  "ch%,pan#" },
  { "ChannelPitch",        "",  "ch%,hz#" },
  { "ChannelPlaying",      "%", "ch%" },
  { "ChannelVolume",       "",  "ch%,vol#" },
  { "Chr",                 "$", "n%" },
  { "ClearTextureFilters", "",  "" },
  { "ClearWorld",          "",  "entities%?,brushes%?,textures%?" },
  { "CloseDir",            "",  "handle%" },
  { "CloseFile",           "",  "handle%" },
  { "Cls",                 "",  "" },
  { "ClsColor",            "",  "r%,g%,b%" },
  { "Color",               "",  "r%,g%,b%" },
  { "ColorBlue",           "%", "" },
  { "ColorGreen",          "%", "" },
  { "ColorRed",            "%", "" },
  { "CommandLine",         "$", "" },
  { "Confirm",             "%", "msg$" },
  { "CopyBank",            "",  "src%,srcOffset%,dst%,dstOffset%,count%" },
  { "CopyFile",            "",  "src$,dst$" },
  { "CopyImage",           "%", "handle%" },
  { "CopyPixel",           "",  "sx%,sy%,sbuf%,dx%,dy%,dbuf%?" },
  { "CopyPixelFast",       "",  "sx%,sy%,sbuf%,dx%,dy%,dbuf%?" },
  { "CopyRect",            "",  "sx%,sy%,sw%,sh%,dx%,dy%,srcbuf%?,dstbuf%?" },
  { "Cos",                 "#", "deg#" },
  { "CountChildren",       "%", "h%" },
  { "CountGfxDrivers",     "%", "" },
  { "CountGfxModes",       "%", "" },
  { "CountGfxModes3D",     "%", "" },
  { "CreateBank",          "%", "size%?" },
  { "CreateCamera",        "%", "parent%?" },
  { "CreateCone",          "%", "segs%?,open%?,parent%?" },
  { "CreateCube",          "%", "parent%?" },
  { "CreateCylinder",      "%", "segs%?,open%?,parent%?" },
  { "CreateDir",           "",  "path$" },
  { "CreateImage",         "%", "w%,h%,nframes%?" },
  { "CreateLight",         "%", "type%?,parent%?" },
  { "CreatePivot",         "%", "parent%?" },
  { "CreateSphere",        "%", "segs%?,parent%?" },
  { "CreateTexture",       "%", "width%,height%,flags%?,frames%?" },
  { "CreateTimer",         "%", "hz%" },
  { "CurrentDate",         "$", "" },
  { "CurrentDir",          "$", "" },
  { "CurrentTime",         "$", "" },
  { "Delay",               "",  "ms%" },
  { "DeleteDir",           "",  "path$" },
  { "DeleteFile",          "",  "path$" },
  { "Dither",              "",  "arg1%" },
  { "DrawBlock",           "",  "handle%,x%,y%,frame%?" },
  { "DrawBlockRect",       "",  "handle%,x%,y%,sx%,sy%,sw%,sh%,frame%?" },
  { "DrawImage",           "",  "handle%,x%,y%,frame%?" },
  { "DrawImageEllipse",    "",  "handle%,x%,y%,rx%,ry%,frame%?" },
  { "DrawImageRect",       "",  "handle%,x%,y%,sx%,sy%,sw%,sh%,frame%?" },
  { "EndGraphics",         "",  "" },
  { "EntityAlpha",         "",  "h%,alpha#" },
  { "EntityAutoFade",      "",  "h%,near_dist#,far_dist#" },
  { "EntityBlend",         "",  "h%,blend%" },
  { "EntityClass",         "$", "h%" },
  { "EntityColor",         "",  "h%,r#,g#,b#" },
  { "EntityDistance",      "#", "h1%,h2%" },
  { "EntityFX",            "",  "h%,fx%" },
  { "EntityName",          "$", "h%" },
  { "EntityOrder",         "",  "h%,order%" },
  { "EntityParent",        "",  "h%,new_parent%,glob%?" },
  { "EntityPitch",         "#", "h%,glob%?" },
  { "EntityRoll",          "#", "h%,glob%?" },
  { "EntityShininess",     "",  "h%,shininess#" },
  { "EntityTexture",       "",  "entity%,texture%,frame%?,index%?" },
  { "EntityX",             "#", "h%,glob%?" },
  { "EntityY",             "#", "h%,glob%?" },
  { "EntityYaw",           "#", "h%,glob%?" },
  { "EntityZ",             "#", "h%,glob%?" },
  { "Eof",                 "%", "handle%" },
  { "ExecFile",            "",  "path$" },
  { "Exp",                 "#", "x#" },
  { "FilePos",             "%", "handle%" },
  { "FileSize",            "%", "path$" },
  { "FileType",            "%", "path$" },
  { "FindChild",           "%", "h%,name$" },
  { "Flip",                "",  "vblank%?" },
  { "FlipImage",           "",  "handle%,frame%?" },
  { "Float",               "#", "s$" },
  { "Floor",               "#", "x#" },
  { "FlushJoy",            "",  "" },
  { "FlushKeys",           "",  "" },
  { "FlushMouse",          "",  "" },
  { "FontHeight",          "%", "" },
  { "FontWidth",           "%", "" },
  { "FreeBank",            "",  "handle%" },
  { "FreeEntity",          "",  "h%" },
  { "FreeFont",            "",  "handle%" },
  { "FreeImage",           "",  "handle%" },
  { "FreeSound",           "",  "snd%" },
  { "FreeTexture",         "",  "texture%" },
  { "FreeTimer",           "",  "handle%" },
  { "FrontBuffer",         "%", "" },
  { "GetChild",            "%", "h%,index%" },
  { "GetColor",            "",  "x%,y%" },
  { "GetEnv",              "$", "key$" },
  { "GetJoy",              "%", "port%?" },
  { "GetKey",              "%", "" },
  { "GetMouse",            "%", "" },
  { "GetParent",           "%", "h%" },
  { "GfxDriverName",       "$", "driver%" },
  { "GfxModeDepth",        "%", "mode%" },
  { "GfxModeExists",       "%", "width%,height%,depth%" },
  { "GfxModeHeight",       "%", "mode%" },
  { "GfxModeWidth",        "%", "mode%" },
  { "GrabImage",           "",  "handle%,x%,y%,frame%?" },
  { "Graphics",            "",  "width%,height%,depth%?,mode%?" },
  { "Graphics3D",          "",  "w%,h%,depth%?,mode%?" },
  { "GraphicsDepth",       "%", "" },
  { "GraphicsHeight",      "%", "" },
  { "GraphicsMode",        "",  "w%,h%,depth%,rate%" },
  { "GraphicsRate",        "%", "" },
  { "GraphicsWidth",       "%", "" },
  { "HandleImage",         "",  "handle%,hx%,hy%" },
  { "Hex",                 "$", "n%" },
  { "HideEntity",          "",  "h%" },
  { "HidePointer",         "",  "" },
  { "HWMultiTex",          "",  "arg1%" },
  { "HWTexUnits",          "%", "" },
  { "ImageBuffer",         "%", "img%,frame%?" },
  { "ImageHeight",         "%", "handle%" },
  { "ImageRectCollide",    "%", "handle%,x%,y%,frame%,rx%,ry%,rw%,rh%" },
  { "ImageRectOverlap",    "%", "handle%,x%,y%,rx%,ry%,rw%,rh%" },
  { "ImagesColl",          "%", "h1%,x1%,y1%,h2%,x2%,y2%" },
  { "ImagesCollide",       "%", "h1%,x1%,y1%,f1%,h2%,x2%,y2%,f2%" },
  { "ImagesOverlap",       "%", "h1%,x1%,y1%,h2%,x2%,y2%" },
  { "ImageWidth",          "%", "handle%" },
  { "ImageXColl",          "%", "h1%,x1%,y1%,h2%,x2%,y2%" },
  { "ImageXHandle",        "%", "handle%" },
  { "ImageYColl",          "%", "h1%,x1%,y1%,h2%,x2%,y2%" },
  { "ImageYHandle",        "%", "handle%" },
  { "Input",               "$", "prompt$?" },
  { "Instr",               "%", "s$,sub$,start%?" },
  { "Int",                 "%", "x" },
  { "JoyDown",             "%", "btn%,port%?" },
  { "JoyHat",              "%", "port%?" },
  { "JoyHit",              "%", "btn%,port%?" },
  { "JoyType",             "%", "port%?" },
  { "JoyU",                "#", "port%?" },
  { "JoyV",                "#", "port%?" },
  { "JoyX",                "#", "port%?" },
  { "JoyY",                "#", "port%?" },
  { "JoyZ",                "#", "port%?" },
  { "KeyDown",             "%", "code%" },
  { "KeyHit",              "%", "code%" },
  { "Left",                "$", "s$,n%" },
  { "Len",                 "%", "s$" },
  { "LightColor",          "",  "light%,r#,g#,b#" },
  { "LightConeAngles",     "",  "light%,inner_angle#,outer_angle#" },
  { "LightRange",          "",  "light%,range#" },
  { "Line",                "",  "x1%,y1%,x2%,y2%" },
  { "ListenerOrientation", "",  "fx#,fy#,fz#,ux#,uy#,uz#" },
  { "ListenerPosition",    "",  "x#,y#,z#" },
  { "ListenerVelocity",    "",  "vx#,vy#,vz#" },
  { "Load3DSound",         "%", "file$" },
  { "LoadAnimImage",       "%", "file$,fw%,fh%,first%,count%" },
  { "LoadAnimTexture",     "%", "file$,flags%,width%,height%,first%,count%" },
  { "LoadBuffer",          "%", "buf%,file$" },
  { "LoadFont",            "%", "name$,height%?,bold%?,italic%?,underline%?" },
  { "LoadImage",           "%", "file$" },
  { "LoadSound",           "%", "file$" },
  { "LoadTexture",         "%", "file$,flags%?" },
  { "Locate",              "",  "x%,y%" },
  { "LockBuffer",          "",  "buf%?" },
  { "Log",                 "#", "x#" },
  { "Log10",               "#", "x#" },
  { "LoopSound",           "",  "snd%" },
  { "Lower",               "$", "s$" },
  { "LSet",                "$", "s$,n%" },
  { "MaskImage",           "",  "handle%,r%,g%,b%" },
  { "Max",                 ".", "a,b" },
  { "MeshDepth",           "#", "h%" },
  { "MeshHeight",          "#", "h%" },
  { "MeshWidth",           "#", "h%" },
  { "Mid",                 "$", "s$,pos%,n%?" },
  { "MidHandle",           "",  "handle%" },
  { "MilliSecs",           "%", "" },
  { "Min",                 ".", "a,b" },
  { "MirrorImage",         "",  "handle%,frame%?" },
  { "MouseDown",           "%", "btn%" },
  { "MouseHit",            "%", "btn%" },
  { "MouseX",              "%", "" },
  { "MouseXSpeed",         "%", "" },
  { "MouseY",              "%", "" },
  { "MouseYSpeed",         "%", "" },
  { "MouseZ",              "%", "" },
  { "MouseZSpeed",         "%", "" },
  { "MoveEntity",          "",  "h%,dx#,dy#,dz#" },
  { "MoveMouse",           "",  "x%,y%" },
  { "MusicPlaying",        "%", "" },
  { "NameEntity",          "",  "h%,name$" },
  { "NextFile",            "$", "handle%" },
  { "Notify",              "",  "msg$" },
  { "OpenFile",            "%", "path$" },
  { "Origin",              "",  "x%,y%" },
  { "Oval",                "",  "x%,y%,w%,h%,solid%?" },
  { "PauseChannel",        "",  "ch%" },
  { "PeekByte",            "%", "handle%,offset%" },
  { "PeekFloat",           "#", "handle%,offset%" },
  { "PeekInt",             "%", "handle%,offset%" },
  { "PeekShort",           "%", "handle%,offset%" },
  { "PlayCDTrack",         "%", "track%,mode%?" },
  { "PlayMusic",           "%", "file$" },
  { "PlaySound",           "%", "snd%" },
  { "Plot",                "",  "x%,y%" },
  { "PointEntity",         "",  "h%,target%,roll#?" },
  { "PokeByte",            "",  "handle%,offset%,val%" },
  { "PokeFloat",           "",  "handle%,offset%,val#" },
  { "PokeInt",             "",  "handle%,offset%,val%" },
  { "PokeShort",           "",  "handle%,offset%,val%" },
  { "PollEvents",          "%", "" },
  { "Poly",                "",  "x0%,y0%,x1%,y1%,x2%,y2%" },
  { "PositionEntity",      "",  "h%,x#,y#,z#,glob%?" },
  { "PositionTexture",     "",  "texture%,u_offset#,v_offset#" },
  { "Print",               ".", "val?" },
  { "Proceed",             "%", "msg$" },
  { "Rand",                "%", "min%,max%?" },
  { "ReadAvail",           "%", "handle%" },
  { "ReadByte",            "%", "handle%" },
  { "ReadBytes",           "%", "bankHandle%,fileHandle%,offset%,count%" },
  { "ReadDir",             "%", "path$" },
  { "ReadFile",            "%", "path$" },
  { "ReadFloat",           "#", "handle%" },
  { "ReadInt",             "%", "handle%" },
  { "ReadLine",            "$", "handle%" },
  { "ReadPixel",           "%", "x%,y%,buf%?" },
  { "ReadPixelFast",       "%", "x%,y%,buf%?" },
  { "ReadShort",           "%", "handle%" },
  { "ReadString",          "$", "handle%" },
  { "Rect",                "",  "x%,y%,w%,h%,solid%?" },
  { "RenderWorld",         "",  "tween#?" },
  { "Replace",             "$", "s$,from$,to$" },
  { "ResetEntity",         "",  "h%" },
  { "ResizeBank",          "",  "handle%,newsize%" },
  { "ResumeChannel",       "",  "ch%" },
  { "Rgb",                 "%", "r%,g%,b%" },
  { "Right",               "$", "s$,n%" },
  { "Rnd",                 "#", "min#,max#?" },
  { "RndSeed",             "%", "" },
  { "RotateEntity",        "",  "h%,rx#,ry#,rz#,glob%?" },
  { "RotateImage",         "",  "handle%,deg#" },
  { "RotateTexture",       "",  "texture%,angle#" },
  { "RSet",                "$", "s$,n%" },
  { "RuntimeError",        "",  "msg$" },
  { "SaveBuffer",          "%", "buf%,file$" },
  { "SaveImage",           "%", "handle%,file$,frame%?" },
  { "ScaleEntity",         "",  "h%,sx#,sy#,sz#,glob%?" },
  { "ScaleImage",          "",  "handle%,sx#,sy#" },
  { "ScaleTexture",        "",  "texture%,u_scale#,v_scale#" },
  { "SeedRnd",             "",  "seed%" },
  { "SeekFile",            "%", "handle%,pos%" },
  { "SetBuffer",           "",  "buf%" },
  { "SetCubeFace",         "",  "texture%,face%" },
  { "SetCubeMode",         "",  "texture%,mode%" },
  { "SetEnv",              "",  "key$,val$" },
  { "SetFont",             "",  "handle%" },
  { "SetGfxDriver",        "",  "driver%" },
  { "Sgn",                 "%", "x#" },
  { "ShowEntity",          "",  "h%" },
  { "ShowPointer",         "",  "" },
  { "Sin",                 "#", "deg#" },
  { "SoundPan",            "",  "snd%,pan#" },
  { "SoundPitch",          "",  "snd%,hz#" },
  { "SoundRange",          "",  "snd%,inner#,outer#" },
  { "SoundVolume",         "",  "snd%,vol#" },
  { "Sqr",                 "#", "x#" },
  { "StopChannel",         "",  "ch%" },
  { "StopMusic",           "",  "" },
  { "Str",                 "$", "n" },
  { "String",              "$", "s$,n%" },
  { "StringHeight",        "%", "s$" },
  { "StringWidth",         "%", "s$" },
  { "SystemProperty",      "$", "prop$" },
  { "Tan",                 "#", "deg#" },
  { "Text",                "",  "x%,y%,s$,centerX%?,centerY%?" },
  { "TextureBlend",        "",  "texture%,blend%" },
  { "TextureBuffer",       "%", "texture%,frame%?" },
  { "TextureCoords",       "",  "texture%,coords%" },
  { "TextureFilter",       "",  "match_text$,texture_flags%?" },
  { "TextureHeight",       "%", "texture%" },
  { "TextureName",         "$", "texture%" },
  { "TextureWidth",        "%", "texture%" },
  { "TileBlock",           "",  "handle%,x%?,y%?,frame%?" },
  { "TileImage",           "",  "handle%,x%?,y%?,frame%?" },
  { "ToFloat",             "#", "s" },
  { "ToInt",               "%", "s" },
  { "TotalVidMem",         "%", "" },
  { "TranslateEntity",     "",  "h%,dx#,dy#,dz#,glob%?" },
  { "Trim",                "$", "s$" },
  { "TrisRendered",        "%", "" },
  { "TurnEntity",          "",  "h%,drx#,dry#,drz#,glob%?" },
  { "UnlockBuffer",        "",  "buf%?" },
  { "UpdateWorld",         "",  "elapsed_time#?" },
  { "Upper",               "$", "s$" },
  { "Viewport",            "",  "x%,y%,w%,h%" },
  { "WaitJoy",             "%", "port%?" },
  { "WaitKey",             "%", "" },
  { "WaitMouse",           "%", "" },
  { "WaitSound",           "",  "ch%" },
  { "WaitTimer",           "%", "handle%" },
  { "WBuffer",             "",  "arg1%" },
  { "Windowed3D",          "%", "" },
  { "Wireframe",           "",  "on%" },
  { "Write",               ".", "val" },
  { "WriteByte",           "",  "handle%,val%" },
  { "WriteBytes",          "%", "bankHandle%,fileHandle%,offset%,count%" },
  { "WriteFile",           "%", "path$" },
  { "WriteFloat",          "",  "handle%,val#" },
  { "WriteInt",            "",  "handle%,val%" },
  { "WriteLine",           "",  "handle%,s$" },
  { "WritePixel",          "",  "x%,y%,color%,buf%?" },
  { "WritePixelFast",      "",  "x%,y%,color%,buf%?" },
  { "WriteShort",          "",  "handle%,val%" },
  { "WriteString",         "",  "handle%,s$" },
};

// Blitz3D is case-insensitive, the generated C++ is not: the runtime function
// for Print is bb_Print, whatever the source spelled. Returns the canonical
// spelling from kCommands[] for any casing of a built-in, or nullptr when the
// name is not a built-in command.
inline const char *canonicalCommand(const std::string &name) {
  static const std::unordered_map<std::string, const char *> byLower = [] {
    std::unordered_map<std::string, const char *> m;
    for (const auto &c : kCommands) m.emplace(toLower(c.name), c.name);
    return m;
  }();
  auto it = byLower.find(toLower(name));
  return (it == byLower.end()) ? nullptr : it->second;
}

// Menschenlesbare Signatur fuer -k / +k: "s$, n%" — das '?' der optionalen
// Parameter wird zu "[...]", damit die Ausgabe lesbar bleibt.
inline std::string commandSignature(const CmdInfo &c) {
  std::string out, rest = c.params;
  size_t pos = 0;
  while (pos < rest.size()) {
    size_t comma = rest.find(',', pos);
    std::string tok = rest.substr(pos, comma == std::string::npos
                                          ? std::string::npos
                                          : comma - pos);
    pos = (comma == std::string::npos) ? rest.size() : comma + 1;
    bool optional = !tok.empty() && tok.back() == '?';
    if (optional) tok.pop_back();
    if (!out.empty()) out += ", ";
    out += optional ? ("[" + tok + "]") : tok;
  }
  return out;
}

#endif // BLITZNEXT_COMMANDS_H
